### ISSUE TITLE
Download SVG/PNG not working on mobile

### ISSUE THREAD

**Issue by ugurdoksan** [appreciated/apexcharts-flow#16]
Download SVG/PNG 

works fine in web browsers 👍 
does not work in mobile browsers 👎 

_I am using the latest version of Chrome browser..._

**Comment by appreciated** [comment]
Is it just pie chart and donut chart for you aswell?

**Comment by ugurdoksan** [comment]
For example Line Chart download button is working on js, but not working on Java in my Android device (Samsung S9+)

**Comment by appreciated** [comment]
Was somehow fixed by upgrading the apex-charts dependency.

**Comment by ugurdoksan** [comment]
@appreciated is not working on my device "Samsung S9+" again

**Comment by appreciated** [comment]
This is a "Tomcat" specific problem. It works when I use the demo which is running with jetty (and without springboot) 🤔 quite wierd. 
Are you also using Spring Boot by any chance?

**Comment by ugurdoksan** [comment]
I do not use Spring Boot with my Vaadin Project @appreciated.

**Comment by appreciated** [comment]
I was able to reproduce the issue. The download does not work when you use the charts f.e. inside of a `form-layout`. So adding the charts to a `div` works just fine. I also found issues when using a VerticalLayout in the offical demo.

**Comment by appreciated** [comment]
So to reproduce the issue with a `Div` simply add `display:flex` to it and the download won't work on mobile devices anymore.

**Comment by appreciated** [comment]
I assume that this has something to do with the fact that I wrapped apexcharts.js inside of a webcomponent.
So I see a few options here, either this is going to be fixed in the [offical repository](https://github.com/apexcharts/apexcharts.js) for which a issue report is necessary with a extensive issue report with an example is necessary. 
Another option is that I remove the webcomponent wrapper an make this as a direct JS dependecy. Either way this is not going to take time, which I currently do not have.

**Comment by appreciated** [comment]
@ugurdoksan This was possibly fixed by the Polymer 3 port, I've got to check back on this be fore releaseing the first 2.0.0 beta

**Comment by appreciated** [comment]
[This issue is fixed in the new version](https://vaadin.com/directory/component/apexchartsjs/2.0.0.beta10)
