### ISSUE TITLE
Legend does not follow chart colors

### ISSUE THREAD

**Issue by markhm** [appreciated/apexcharts-flow#61]
The generated legend for a `VerticalBarChart` does not follow the chart colors, see:

![stacked_bar_chart](https://user-images.githubusercontent.com/1430451/78558860-a075ae00-7813-11ea-9d6b-29d53139f3a8.png)

Legend is added as follows:

```
LegendBuilder legendBuilder = LegendBuilder.get();
Labels labels = new Labels();
labels.setUseSeriesColors(true);
legendBuilder.withLabels(labels);

// withChart call uses the legendBuilder:
...
.withLegend(legendBuilder.build())
...
```

It is expected that the legend elements follow the chart colors. 

Found in version 2.0.0.beta9.

**Comment by appreciated** [comment]
@markhm have you checked if this also happens when using ApexCharts.js directly (Try on CodePen)[https://codepen.io/apexcharts/pen/bxzgZJ]? If so this is a bug for the official repository not for the wrapper.

**Comment by markhm** [comment]
It seems that ApexCharts.js itself works correctly, see https://codepen.io/markhm/pen/ExjqYbV (example from the original ApexCharts examples).

**Comment by higgsja** [comment]
I have the same issue with a line chat.

**Comment by appreciated** [comment]
@markhm I am not able to reproduce your issue. 
[Since you haven't provided a code example I created a working one. Maybe you are able to reproduce your issue with it.](https://github.com/appreciated/apexcharts-flow/blob/master/src/test/java/com/github/appreciated/apexcharts/VerticalBarChartColoredExampleView.java)
